@hostname = http://localhost:5000/api

### Register a new user
POST {{hostname}}/auth/register
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@gmail.com",
  "password": "admin@123"  
}

### Admin login
POST {{hostname}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin@123"
}

### Employee login
POST {{hostname}}/auth/login
Content-Type: application/json

{
  "email": "dhana@example.com",
  "password": "password123"
}



### Create a new company
POST {{hostname}}/companies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODk5NmQzZDNjNDUyNjA2NDMzOGQxYSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc3MDk1OTI2MCwiZXhwIjoxNzcwOTYwMTYwfQ.lJ3xe4mTNycIsMjbXnTUscYoahYBpnw_HnQeSDyzzEE

{
    "name": "BrightWave Media",
    "address": "19 Sunset Boulevard, Los Angeles, CA 90028",
    "addressLink": "https://www.google.com/maps?ll=6.923697,79.85034&z=21&t=m&hl=en&gl=LK&mapclient=embed&cid=11707078475898616978",
    "contactPerson": "Dhananjaya",
    "contactNumber": "555-123-4567",
    "assignedUser":"6979d2f3fa74325559966f74"
}



### Get all companies 
### must login to the system to get the token and use it in the authorization header
GET {{hostname}}/companies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NzlkMmYzZmE3NDMyNTU1OTk2NmY3NCIsInJvbGUiOiJFbXBsb3llZSIsImlhdCI6MTc3MDk2MjU0NiwiZXhwIjoxNzcwOTYzNDQ2fQ.4pryNtOQgY1S2gvZ1HR-wjm3fMuh6_RuZns8YfkkAPM
### Get company by ID
GET {{hostname}}/companies/6989a1c6b61cadf24e13ac05
Authorization: Bearer 



### Update company details
PUT {{hostname}}/companies/6989a1c6b61cadf24e13ac05
Content-Type: application/json
Authorization: Bearer 

{
    "contactNumber": "555-987-6543",
    "assignedUser":"698996d3d3c4526064338d1a"
}


### Delete a company
DELETE {{hostname}}/companies/6989a1c6b61cadf24e13ac05
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODk5NmQzZDNjNDUyNjA2NDMzOGQxYSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc3MDYyNzg3MywiZXhwIjoxNzcwNjI4NzczfQ.dWs5D6fxsKyjoZNj0zrHlTsf0GZT9mLfKr3Z4vQfSNQ